fieldLayouts:
  14c1d6a3-9e1b-4c7c-8345-04f398c5de97:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: fdb104fd-ff62-4ed6-8ab1-66919874710d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 213c62f5-0e14-4bd7-89fd-d8555f5fef5b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 8a1c1e99-fcfd-4d7d-bb43-4856928f370c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Seo
        sortOrder: 2
handle: careers
hasTitleField: true
name: Careers
section: 239c0b70-dc95-4ffe-a9da-d2997d59235f
sortOrder: 0
titleFormat: null
