fieldLayouts:
  721f03e3-d9c8-4d4d-8109-a57ae2980e11:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Brand Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 7b0a4177-ed87-4ce5-8d29-ddee1f00dbbc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c48a2fb5-6ee2-4bbc-a652-59cffd8d3678
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 44a4324c-ff7d-4108-9184-ca7629283a5b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9759d04-7457-4793-808b-ec0c47a2fdc8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            heading: Appointment
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: a1419e7b-5082-412c-adb0-fd8d09db0b92
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            heading: 'Content Restrictions'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 5c43166e-154f-4961-84a8-3db156b513b7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            heading: 'Social Handles'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 08c20f5f-9281-4032-b9ef-ab8485217cda
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d51a9b09-1ae0-4106-8446-09acecee11c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Collection
        sortOrder: 2
      -
        elements:
          -
            fieldUid: a3ff0203-8bd7-4afa-8ae9-2294faa2988b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Videos
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 6983d58a-4697-42f9-9db7-bbcc6bab4025
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Catalogue
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 4a84f73f-f24f-4c68-a2b1-cd6a71442ce8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 5
handle: lfw2020Designers
hasTitleField: true
name: 'LFW2020 Designers'
section: 8be64add-0237-4543-9a61-01067d725393
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
