fieldLayouts:
  dc338241-b7c3-4440-8f3e-87b35b271210:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 8a1c1e99-fcfd-4d7d-bb43-4856928f370c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Seo
        sortOrder: 1
handle: publicationsLanding
hasTitleField: true
name: 'Publications Landing'
section: c576b6d5-0f68-48d2-be41-2e216f725ba2
sortOrder: 0
titleFormat: null
