version: "3.7"
services:
  php-fpm:
    container_name: lfw-php
    build: ./
    # image: craftcms/php-fpm:7.4-dev
    user: "www-data:www-data"
    volumes:
    - ./app:/app:cached
    env_file: .env
  nginx:
    container_name: lfw-nginx
    image: nginx:stable-alpine
    # user: "www-data:www-data"
    ports:
      - 8000:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./app:/app:cached
  console:
    container_name: lfw-console
    image: craftcms/cli:7.4-dev
    user: "www-data:www-data"
    volumes:
      - ./app:/app:cached
    env_file: .env
    command: ["./craft", "queue/listen"]
  mariadb:
    container_name: lfw-db
    image: mariadb:10.5.6-focal
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql:delegated
  redis:
    container_name: lfw-redis
    image: redis:5-alpine
    ports:
      - 6379:6379
volumes:
  db_data: