contentColumnType: text
fieldGroup: 61184f31-482d-4875-9ff8-bc9e92525667
handle: awards
instructions: ''
name: Awards
searchable: true
settings:
  addRowLabel: 'Add award'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Item
            -
              - handle
              - item
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
