contentColumnType: string
fieldGroup: 10d70fe8-86c0-4e8d-8f03-856feb15a215
handle: catalogue
instructions: ''
name: Catalogue
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 2b582fba-ff25-4e51-8cab-08fb4ff5a1c3
        -
          __assoc__:
            -
              - width
              - ''
      -
        - fbec7e1b-dc55-46cb-a3cc-117de7f17b4d
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c677c472-2223-4399-9d24-658432b4267f
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 44505e6b-9f68-45e2-b2ea-274cc50c6b9b
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_catalogue}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
