contentColumnType: string
fieldGroup: 48fce0ca-0fdc-4329-9939-5cf39c034bcf
handle: clients
instructions: 'Enter client assets. Name and Logo'
name: Clients
searchable: true
settings:
  contentTable: '{{%matrixcontent_clients}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
