contentColumnType: smallint(3)
fieldGroup: ef16fc4e-fda0-454f-85c6-74b00da1e814
handle: collectionPerPage
instructions: ''
name: 'Collection Per Page'
searchable: false
settings:
  decimals: 0
  defaultValue: '24'
  max: '100'
  min: '1'
  prefix: ''
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
