contentColumnType: string
fieldGroup: 10d70fe8-86c0-4e8d-8f03-856feb15a215
handle: collection
instructions: 'Upload the designer''s collection'
name: Collection
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:66c3e47f-3fe3-4a98-9461-77cc9794eccd'
  defaultUploadLocationSubpath: 'designers/{title}/collection'
  limit: ''
  localizeRelations: false
  previewMode: thumbs
  restrictFiles: '1'
  selectionLabel: 'Upload the designer''s colection'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:66c3e47f-3fe3-4a98-9461-77cc9794eccd'
  singleUploadLocationSubpath: 'designers/{slug}/collection'
  source: null
  sources:
    - 'volume:66c3e47f-3fe3-4a98-9461-77cc9794eccd'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
