contentColumnType: text
fieldGroup: 61184f31-482d-4875-9ff8-bc9e92525667
handle: consultancyRecord
instructions: ''
name: 'Consultancy Record'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - handle
              - item
            -
              - heading
              - Item
            -
              - type
              - singleline
            -
              - width
              - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
