contentColumnType: string
fieldGroup: 61184f31-482d-4875-9ff8-bc9e92525667
handle: intro
instructions: ''
name: Intro
searchable: true
settings:
  cleanupHtml: '1'
  columnType: text
  configFile: Simple.json
  purifyHtml: ''
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
