contentColumnType: string
fieldGroup: 10d70fe8-86c0-4e8d-8f03-856feb15a215
handle: restrictions
instructions: ''
name: Restrictions
searchable: false
settings:
  contentTable: '{{%stc_restrictions}}'
  fieldLayout: matrix
  maxRows: '1'
  minRows: '1'
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
