contentColumnType: text
fieldGroup: 34165791-a73c-44b1-922a-3e199f916215
handle: seo
instructions: ''
name: SEO
searchable: true
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogType
    - ogDescription
    - ogImage
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - seoImageTransformMode
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterEnabledFields:
    - seoPreview
    - twitterCardType
    - transformTwitterImage
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
