contentColumnType: string
fieldGroup: ef16fc4e-fda0-454f-85c6-74b00da1e814
handle: sponsors
instructions: ''
name: Sponsors
searchable: false
settings:
  contentTable: '{{%matrixcontent_sponsors}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
