contentColumnType: string
fieldGroup: 10d70fe8-86c0-4e8d-8f03-856feb15a215
handle: videos
instructions: ''
name: Videos
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - json
    - video
  defaultUploadLocationSource: 'volume:66c3e47f-3fe3-4a98-9461-77cc9794eccd'
  defaultUploadLocationSubpath: 'designers/{slug}/videos'
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Upload the designer videos'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:66c3e47f-3fe3-4a98-9461-77cc9794eccd'
  singleUploadLocationSubpath: 'designers/{slug}/videos'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
