fieldLayouts:
  106d8be8-bf93-4aa7-913d-1cea8e7b7f68:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: icons
hasUrls: true
name: Icons
settings:
  path: assets/icons
sortOrder: 6
type: craft\volumes\Local
url: /assets/icons
