fieldLayouts:
  1486b7a1-f012-46e9-9de5-7cb320c6de3c:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'Upload the current season''s details'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 442ac823-c336-4cf2-a2e2-58a88a6bd78d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Current Season Sponsors'
        sortOrder: 1
handle: sponsors
name: Sponsors
