handle: currentSeason
instructions: 'Navigation for the current season of fashion week'
maxNodes: ''
name: 'Current Season'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
siteSettings:
  00accd63-95d7-4b22-b81f-1c537016045f: null
sortOrder: 2
structure:
  maxLevels: null
  uid: a0c4263c-f062-473f-bbcc-99dcd6eed565
