field: 5c43166e-154f-4961-84a8-3db156b513b7
fieldLayouts:
  c9219bff-af49-4fae-b47b-a042622ed252:
    tabs:
      -
        elements:
          -
            fieldUid: 5a321b0b-dd57-4d6a-94f1-2db7fca06790
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f2b9a0c-6cea-495c-9ee7-f4aaa2d38c68
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 97a8793e-a092-4bb6-b974-845e2e10ebb4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 49699eea-494e-434d-8813-36b0596c1f6a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2f2b9a0c-6cea-495c-9ee7-f4aaa2d38c68:
    contentColumnType: boolean
    fieldGroup: null
    handle: catalogue
    instructions: ''
    name: Catalogue
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  49699eea-494e-434d-8813-36b0596c1f6a:
    contentColumnType: text
    fieldGroup: null
    handle: password
    instructions: ''
    name: Password
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5a321b0b-dd57-4d6a-94f1-2db7fca06790:
    contentColumnType: boolean
    fieldGroup: null
    handle: collection
    instructions: ''
    name: Collection
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  97a8793e-a092-4bb6-b974-845e2e10ebb4:
    contentColumnType: boolean
    fieldGroup: null
    handle: videos
    instructions: ''
    name: Videos
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
