field: 08c20f5f-9281-4032-b9ef-ab8485217cda
fieldLayouts:
  f55825c9-a80d-46c4-96b0-f6b4a51624f0:
    tabs:
      -
        elements:
          -
            fieldUid: a594f6a5-c596-49a9-aadc-8a12f49fcfd3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdd4d4e0-eae9-443b-89cf-1cb0760facee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5560d053-7b5e-459b-828b-545f8b137560
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6bcc939-1994-4d3e-be57-25478dc786fe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5560d053-7b5e-459b-828b-545f8b137560:
    contentColumnType: string(255)
    fieldGroup: null
    handle: instagram
    instructions: ''
    name: Instagram
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a594f6a5-c596-49a9-aadc-8a12f49fcfd3:
    contentColumnType: string(255)
    fieldGroup: null
    handle: twitter
    instructions: ''
    name: Twitter
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  b6bcc939-1994-4d3e-be57-25478dc786fe:
    contentColumnType: string(255)
    fieldGroup: null
    handle: youtube
    instructions: ''
    name: Youtube
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  fdd4d4e0-eae9-443b-89cf-1cb0760facee:
    contentColumnType: string(255)
    fieldGroup: null
    handle: facebook
    instructions: ''
    name: Facebook
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
