enableVersioning: true
handle: casesAndResultsLanding
name: 'Cases and Results Landing'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  3e993b0c-6b63-496e-9fa9-e9dbb42c592b:
    enabledByDefault: true
    hasUrls: true
    template: cases-and-results
    uriFormat: cases-and-results
type: single
