enableVersioning: true
handle: casesAndResults
name: 'Cases and Results'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  3e993b0c-6b63-496e-9fa9-e9dbb42c592b:
    enabledByDefault: true
    hasUrls: true
    template: cases-and-results/_entry
    uriFormat: '{% if object.level == 1 %}cases-and-results/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: ab8316d6-12a7-44e5-9c4b-34b8d77b4d7b
type: structure
