enableVersioning: true
handle: lfw2020DesignersLanding
name: 'LFW2020 Designers Landing'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  00accd63-95d7-4b22-b81f-1c537016045f:
    enabledByDefault: true
    hasUrls: true
    template: lfw2020/designers/index
    uriFormat: lfw2020/designers
type: single
